<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="swing" nsURI="http://www.example.org/swing" nsPrefix="swing">
  <eClassifiers xsi:type="ecore:EClass" name="Controlador">
    <eStructuralFeatures xsi:type="ecore:EReference" name="modelo" upperBound="-1"
        eType="#//Modelo" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="vista" upperBound="-1"
        eType="#//Vista" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Nombre" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Vista">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ventana" upperBound="-1"
        eType="#//Ventana" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Nombre" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Modelo">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Nombre" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="clase" upperBound="-1"
        eType="#//Clase" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Ventana">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="jpanel" upperBound="-1"
        eType="#//JPanel" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="JPanel">
    <eStructuralFeatures xsi:type="ecore:EReference" name="jtextfield" eType="#//JTextField"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="jbutton" eType="#//JButton"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="jlable" eType="#//JLable"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="jcombobox" eType="#//JComboBox"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="jtable" eType="#//JTable"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="JComboBox">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Contenido" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="JButton">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Text" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="JTextField">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="JLable">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="JTable">
    <eStructuralFeatures xsi:type="ecore:EReference" name="thead" upperBound="-1"
        eType="#//THead" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="tbody" upperBound="-1"
        eType="#//TBody" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="THead">
    <eStructuralFeatures xsi:type="ecore:EReference" name="tr" upperBound="-1" eType="#//Tr"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TBody">
    <eStructuralFeatures xsi:type="ecore:EReference" name="tr" upperBound="-1" eType="#//Tr"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Tr">
    <eStructuralFeatures xsi:type="ecore:EReference" name="td" upperBound="-1" eType="#//Td"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Td">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Entidad">
    <eStructuralFeatures xsi:type="ecore:EReference" name="controlador" upperBound="-1"
        eType="#//Controlador" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Nombre" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Proyecto">
    <eStructuralFeatures xsi:type="ecore:EReference" name="entidad" upperBound="-1"
        eType="#//Entidad" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Nombre" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Clase">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Nombre" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="atributo" upperBound="-1"
        eType="#//Atributo" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="metodo" upperBound="-1"
        eType="#//Metodo" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Atributo">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Nombre" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Visibilidad" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Tipo" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Metodo">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Nombre" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Visibilidad" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Tipo" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
</ecore:EPackage>
